CREATE TABLE dbo.PRODUTO (
    CO_PRODUTO INT NOT NULL PRIMARY KEY,
    NO_PRODUTO VARCHAR(200) NOT NULL,
    PC_TAXA_JUROS NUMERIC(10,9) NOT NULL,
    NU_MINIMO_MESES SMALLINT NOT NULL,
    NU_MAXIMO_MESES SMALLINT NULL, 
    VR_MINIMO NUMERIC(18,2) NOT NULL,
    VR_MAXIMO NUMERIC(18,2) NULL
);
GO