

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SIMULACAO](
	[CO_SIMULACAO] [bigint] IDENTITY(1,1) NOT NULL,
	[PRODUTO_CO_PRODUTO] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SIMULACAO] ADD PRIMARY KEY CLUSTERED 
(
	[CO_SIMULACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SIMULACAO]  WITH CHECK ADD  CONSTRAINT [FKb8hbuiv8jj5e8li8p4b2dknbf] FOREIGN KEY([PRODUTO_CO_PRODUTO])
REFERENCES [dbo].[PRODUTO] ([CO_PRODUTO])
GO
ALTER TABLE [dbo].[SIMULACAO] CHECK CONSTRAINT [FKb8hbuiv8jj5e8li8p4b2dknbf]
GO
