

CREATE TABLE dbo.SIMULACAO (
	CO_SIMULACAO INT NOT NULL PRIMARY KEY,
	PRODUTO_CO_PRODUTO INT NULL
) 
GO
ALTER TABLE dbo.SIMULACAO  WITH CHECK ADD  CONSTRAINT [FKb8hbuiv8jj5e8li8p4b2dknbf] FOREIGN KEY(PRODUTO_CO_PRODUTO)
REFERENCES dbo.PRODUTO (CO_PRODUTO)
GO
ALTER TABLE dbo.SIMULACAO CHECK CONSTRAINT [FKb8hbuiv8jj5e8li8p4b2dknbf]
GO
