SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESULTADO_SIMULACAO](
	[CO_SIMULACAO] [bigint] NOT NULL,
	[NU_PARCELA] [int] NOT NULL,
	[VR_AMORTIZACAO] [float] NOT NULL,
	[VR_JUROS] [float] NOT NULL,
	[VR_PRESTACAO] [float] NOT NULL,
	[TP_SISTEMA_AMORTIZACAO] [varchar](255) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RESULTADO_SIMULACAO]  WITH CHECK ADD  CONSTRAINT [FK4wwv615mkw86o8eura413hqqw] FOREIGN KEY([CO_SIMULACAO])
REFERENCES [dbo].[simulacao] ([co_simulacao])
GO
ALTER TABLE [dbo].[RESULTADO_SIMULACAO] CHECK CONSTRAINT [FK4wwv615mkw86o8eura413hqqw]
GO
ALTER TABLE [dbo].[RESULTADO_SIMULACAO]  WITH CHECK ADD CHECK  (([TP_SISTEMA_AMORTIZACAO]='PRICE' OR [TP_SISTEMA_AMORTIZACAO]='SAC'))
GO
