CREATE TABLE dbo.SISTEMA_AMORTIZACAO(
	ID INT IDENTITY(1,1) NOT NULL,
	TP_SISTEMA_AMORTIZACAO VARCHAR(5) NOT NULL,
	SIMULACAO_CO_SIMULACAO INT NULL
) 
GO
ALTER TABLE dbo.SISTEMA_AMORTIZACAO ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE dbo.SISTEMA_AMORTIZACAO  WITH CHECK ADD  CONSTRAINT [FKmspe8j5f3eqa07ul2i189gl8y] FOREIGN KEY(SIMULACAO_CO_SIMULACAO)
REFERENCES dbo.SIMULACAO (CO_SIMULACAO)
GO
ALTER TABLE dbo.SISTEMA_AMORTIZACAO CHECK CONSTRAINT [FKmspe8j5f3eqa07ul2i189gl8y]
GO
ALTER TABLE dbo.SISTEMA_AMORTIZACAO  WITH CHECK ADD CHECK  ((TP_SISTEMA_AMORTIZACAO='PRICE' OR TP_SISTEMA_AMORTIZACAO='SAC'))
GO
