CREATE TABLE dbo.SISTEMA_AMORTIZACAO_PARCELAS(
	SISTEMA_AMORTIZACAO_ID INT NOT NULL,
	NU_PARCELA INT NOT NULL,
	VR_AMORTIZACAO NUMERIC(18,2) NOT NULL,
	VR_JUROS NUMERIC(18,2) NOT NULL,
	VR_PRESTACAO NUMERIC(18,2) NOT NULL
) 
GO
ALTER TABLE dbo.SISTEMA_AMORTIZACAO_PARCELAS  WITH CHECK ADD  CONSTRAINT [FK59wgh1giiiounxr9wo7s4uxn] FOREIGN KEY(SISTEMA_AMORTIZACAO_ID)
REFERENCES dbo.SISTEMA_AMORTIZACAO (id)
GO
ALTER TABLE dbo.SISTEMA_AMORTIZACAO_PARCELAS CHECK CONSTRAINT [FK59wgh1giiiounxr9wo7s4uxn]
GO
