CREATE TABLE dbo.METRICA_SERVICO(
	ID INT IDENTITY(1,1) NOT NULL,
	ENDPOINT VARCHAR(60) NULL,
	REQUEST_METHOD VARCHAR(60) NULL,
	RESPONSE_TIME_MS BIGINT NULL,
	NOME_SERVICO VARCHAR(60) NULL,
	STATUS_CODE INT NULL,
	TIMESTAMP DATETIME2(6) NULL
) 
GO
ALTER TABLE dbo.METRICA_SERVICO ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
